I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 952, in script
    unknow "Vous avez décidé de laisser votre place à Sven. Vous avez beaucoup de courage. Vous rendez vous compte que vous lui avez tout donné."
Exception: Sayer 'unknow' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 952, in script
    unknow "Vous avez décidé de laisser votre place à Sven. Vous avez beaucoup de courage. Vous rendez vous compte que vous lui avez tout donné."
  File "C:\Users\admin_machine\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\admin_machine\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'unknow' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Luleå 1.0
Mon Jan  1 23:11:41 2024
